FROM python:3.10-slim

WORKDIR /app
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
RUN pip install xgboost 

COPY src/ /app/src/
COPY data/ /app/data/

CMD ["python", "src/train_model.py"]
