FROM python:3.10-slim

WORKDIR /app
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Overwrite fastapi / uvicorn specifically just in case
RUN pip install fastapi uvicorn xgboost 

COPY api/ /app/api/
COPY models/ /app/models/

CMD ["uvicorn", "api.app:app", "--host", "0.0.0.0", "--port", "8000"]
